// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
void ui_event_ButtonTime(lv_event_t * e);
lv_obj_t * ui_ButtonTime;
lv_obj_t * ui_LabelTime;
void ui_event_ButtonBloodHeart(lv_event_t * e);
lv_obj_t * ui_ButtonBloodHeart;
lv_obj_t * ui_LabelBloodHeart;


// SCREEN: ui_ScreenTime
void ui_ScreenTime_screen_init(void);
void ui_event_ScreenTime(lv_event_t * e);
lv_obj_t * ui_ScreenTime;
lv_obj_t * ui_ArcTimeSeconds;
lv_obj_t * ui_LabelTimes;


// SCREEN: ui_ScreenBloodHeart
void ui_ScreenBloodHeart_screen_init(void);
void ui_event_ScreenBloodHeart(lv_event_t * e);
lv_obj_t * ui_ScreenBloodHeart;
lv_obj_t * ui_LabelHeartPre;
lv_obj_t * ui_LabelHeart;
lv_obj_t * ui_LabelBloodPre;
lv_obj_t * ui_LabelBlood;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenTime, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTime_screen_init);
    }
}
void ui_event_ButtonTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenTime, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTime_screen_init);
    }
}
void ui_event_ButtonBloodHeart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenBloodHeart, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenBloodHeart_screen_init);
    }
}
void ui_event_ScreenTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ScreenBloodHeart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenTime, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTime_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_ScreenTime_screen_init();
    ui_ScreenBloodHeart_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
