// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project3

#ifndef _SQUARELINE_PROJECT3_UI_H
#define _SQUARELINE_PROJECT3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
void ui_event_ButtonTime(lv_event_t * e);
extern lv_obj_t * ui_ButtonTime;
extern lv_obj_t * ui_LabelTime;
void ui_event_ButtonBloodHeart(lv_event_t * e);
extern lv_obj_t * ui_ButtonBloodHeart;
extern lv_obj_t * ui_LabelBloodHeart;
// SCREEN: ui_ScreenTime
void ui_ScreenTime_screen_init(void);
void ui_event_ScreenTime(lv_event_t * e);
extern lv_obj_t * ui_ScreenTime;
extern lv_obj_t * ui_ArcTimeSeconds;
extern lv_obj_t * ui_LabelTimes;
// SCREEN: ui_ScreenBloodHeart
void ui_ScreenBloodHeart_screen_init(void);
void ui_event_ScreenBloodHeart(lv_event_t * e);
extern lv_obj_t * ui_ScreenBloodHeart;
extern lv_obj_t * ui_LabelHeartPre;
extern lv_obj_t * ui_LabelHeart;
extern lv_obj_t * ui_LabelBloodPre;
extern lv_obj_t * ui_LabelBlood;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
