// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: first_pro

#include "../ui.h"

void ui_ShowTime_screen_init(void)
{
    ui_ShowTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ShowTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
