// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project3

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonTime = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonTime, 74);
    lv_obj_set_height(ui_ButtonTime, 41);
    lv_obj_set_x(ui_ButtonTime, -54);
    lv_obj_set_y(ui_ButtonTime, -55);
    lv_obj_set_align(ui_ButtonTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_ButtonTime);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "time");

    ui_ButtonBloodHeart = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonBloodHeart, 75);
    lv_obj_set_height(ui_ButtonBloodHeart, 37);
    lv_obj_set_x(ui_ButtonBloodHeart, 53);
    lv_obj_set_y(ui_ButtonBloodHeart, -54);
    lv_obj_set_align(ui_ButtonBloodHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBloodHeart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBloodHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBloodHeart = lv_label_create(ui_ButtonBloodHeart);
    lv_obj_set_width(ui_LabelBloodHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBloodHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBloodHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBloodHeart, "blood");

    lv_obj_add_event_cb(ui_ButtonTime, ui_event_ButtonTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBloodHeart, ui_event_ButtonBloodHeart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
