// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project3

#include "../ui.h"

void ui_ScreenBloodHeart_screen_init(void)
{
    ui_ScreenBloodHeart = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBloodHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHeartPre = lv_label_create(ui_ScreenBloodHeart);
    lv_obj_set_width(ui_LabelHeartPre, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeartPre, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeartPre, -59);
    lv_obj_set_y(ui_LabelHeartPre, -56);
    lv_obj_set_align(ui_LabelHeartPre, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeartPre, "Heart:");

    ui_LabelHeart = lv_label_create(ui_ScreenBloodHeart);
    lv_obj_set_width(ui_LabelHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeart, 5);
    lv_obj_set_y(ui_LabelHeart, -56);
    lv_obj_set_align(ui_LabelHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeart, "00");

    ui_LabelBloodPre = lv_label_create(ui_ScreenBloodHeart);
    lv_obj_set_width(ui_LabelBloodPre, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBloodPre, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBloodPre, -61);
    lv_obj_set_y(ui_LabelBloodPre, -15);
    lv_obj_set_align(ui_LabelBloodPre, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBloodPre, "Blood:");

    ui_LabelBlood = lv_label_create(ui_ScreenBloodHeart);
    lv_obj_set_width(ui_LabelBlood, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBlood, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBlood, 10);
    lv_obj_set_y(ui_LabelBlood, -15);
    lv_obj_set_align(ui_LabelBlood, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBlood, "00%");

    lv_obj_add_event_cb(ui_ScreenBloodHeart, ui_event_ScreenBloodHeart, LV_EVENT_ALL, NULL);

}
