// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: first_pro

#ifndef _FIRST_PRO_UI_H
#define _FIRST_PRO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Start
void ui_Start_screen_init(void);
extern lv_obj_t * ui_Start;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_uiArcTimechina;
extern lv_obj_t * ui_uiLabelTimeChina;
// SCREEN: ui_LockScreen
void ui_LockScreen_screen_init(void);
extern lv_obj_t * ui_LockScreen;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_ShowTime
void ui_ShowTime_screen_init(void);
extern lv_obj_t * ui_ShowTime;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1670719189);    // assets/camera-imageonline.co-9391366.png
LV_IMG_DECLARE(ui_img_1886717116);    // assets/b5138bbf-3e31-425d-8658-6123bacb1544.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
