// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: first_pro

#include "../ui.h"

void ui_Start_screen_init(void)
{
    ui_Start = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0xCCD7DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Start);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 3);
    lv_obj_set_y(ui_Slider2, 87);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);


    ui_uiArcTimechina = lv_arc_create(ui_Start);
    lv_obj_set_width(ui_uiArcTimechina, 150);
    lv_obj_set_height(ui_uiArcTimechina, 150);
    lv_obj_set_x(ui_uiArcTimechina, 7);
    lv_obj_set_y(ui_uiArcTimechina, -33);
    lv_obj_set_align(ui_uiArcTimechina, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_uiArcTimechina, 0, 59);
    lv_arc_set_value(ui_uiArcTimechina, 0);
    lv_arc_set_bg_angles(ui_uiArcTimechina, 0, 360);
    lv_arc_set_rotation(ui_uiArcTimechina, 270);


    ui_uiLabelTimeChina = lv_label_create(ui_uiArcTimechina);
    lv_obj_set_width(ui_uiLabelTimeChina, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelTimeChina, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelTimeChina, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelTimeChina, "11:50");

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}
